### ISSUE TITLE
No scrolling in left vertical menu

### ISSUE THREAD

**Issue by arsho** [secondtruth/startmin#12]
Users can not scroll through the left menu. Even if first level of the menu is opened, others options below are being hidden as we can not scroll it.

Google Chrome
Version 76.0.3809.100 (Official Build) (64-bit)
Windows 10
Screen size 14"

Tested in: http://secondtruth.github.io/startmin/pages/tables.html

**Comment by spreaderman** [comment]
Yes, same problem.  Would be great to have fix.

**Comment by quacrom-old** [comment]
```
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
..............
<ul class="nav" id="side-menu">
..........
</ul>
</nav>
```

change and move ul tag content to:

```
<nav class="navbar navbar-inverse1 navbar-fixed-top" role="navigation">
..............
</nav>

<aside id="sidebar" class="sidebar">
<ul class="nav" id="side-menu">
......
</ul>
</aside>
```
